import { jsPDF } from 'jspdf';
import {
  compositeChartCanvas,
  resolveOpaqueBackground,
  contrastTextColor,
  downloadDataUrl,
  slugifyTitle,
} from './canvas-export';

const PDF_GRID_WIDTH = 1600;
const PDF_MARGIN = 32;
const PDF_HEADER_HEIGHT = 64;

const SLIDE_WIDTH = 1920;
const SLIDE_HEIGHT = 1080;
const SLIDE_PADDING = 80;
const SLIDE_TITLE_HEIGHT = 120;
const SLIDE_FONT = '600 44px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';

function delay(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Exports the dashboard grid as a single-page PDF: each chart composited
 * onto the page at its on-screen position and size (scaled to a fixed page
 * width), under a header with the dashboard title — a print/share-ready
 * snapshot of the dashboard as laid out on screen.
 */
export function exportDashboardAsPDF(gridEl: HTMLElement, title: string): boolean {
  const containerRect = gridEl.getBoundingClientRect();
  if (!containerRect.width || !containerRect.height) return false;

  const pageBg = resolveOpaqueBackground(gridEl);
  const textColor = contrastTextColor(pageBg.rgb);

  const charts: { canvas: HTMLCanvasElement; x: number; y: number; w: number; h: number }[] = [];
  for (const child of Array.from(gridEl.children)) {
    const cell = child as HTMLElement;
    const canvas = compositeChartCanvas(cell);
    if (!canvas) continue;
    const rect = cell.getBoundingClientRect();
    charts.push({
      canvas,
      x: rect.left - containerRect.left,
      y: rect.top - containerRect.top,
      w: rect.width,
      h: rect.height,
    });
  }
  if (!charts.length) return false;

  const scale = PDF_GRID_WIDTH / containerRect.width;
  const gridHeight = containerRect.height * scale;
  const pageWidth = PDF_GRID_WIDTH + PDF_MARGIN * 2;
  const pageHeight = PDF_HEADER_HEIGHT + gridHeight + PDF_MARGIN * 2;

  const doc = new jsPDF({
    orientation: pageWidth >= pageHeight ? 'landscape' : 'portrait',
    unit: 'px',
    format: [pageWidth, pageHeight],
  });

  doc.setFillColor(pageBg.rgb[0], pageBg.rgb[1], pageBg.rgb[2]);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.setFontSize(28);
  doc.text(title, PDF_MARGIN, PDF_MARGIN + 24);

  for (const chart of charts) {
    doc.addImage(
      chart.canvas,
      'PNG',
      PDF_MARGIN + chart.x * scale,
      PDF_HEADER_HEIGHT + PDF_MARGIN + chart.y * scale,
      chart.w * scale,
      chart.h * scale
    );
  }

  doc.setFontSize(11);
  doc.text(`Generated by VisualMe · ${new Date().toLocaleDateString()}`, PDF_MARGIN, pageHeight - 14);

  doc.save(`${slugifyTitle(title, 'dashboard')}.pdf`);
  return true;
}

/**
 * Exports each chart in the dashboard as its own 16:9 PNG "slide" — the
 * chart centered below a title bar on the dashboard's background, sized for
 * dropping straight into a deck. Returns the number of slides exported.
 */
export async function exportDashboardAsSlidePNGs(
  gridEl: HTMLElement,
  titles: string[],
  dashboardTitle: string
): Promise<number> {
  const pageBg = resolveOpaqueBackground(gridEl);
  const textColor = contrastTextColor(pageBg.rgb);
  const bgStyle = `rgb(${pageBg.rgb.join(',')})`;
  const textStyle = `rgb(${textColor.join(',')})`;

  const cells = Array.from(gridEl.children) as HTMLElement[];
  let exported = 0;

  for (let i = 0; i < cells.length; i++) {
    const chartCanvas = compositeChartCanvas(cells[i]);
    if (!chartCanvas) continue;

    const slide = document.createElement('canvas');
    slide.width = SLIDE_WIDTH;
    slide.height = SLIDE_HEIGHT;
    const ctx = slide.getContext('2d');
    if (!ctx) continue;

    ctx.fillStyle = bgStyle;
    ctx.fillRect(0, 0, SLIDE_WIDTH, SLIDE_HEIGHT);

    const slideTitle = titles[i] || `Chart ${i + 1}`;
    ctx.fillStyle = textStyle;
    ctx.font = SLIDE_FONT;
    ctx.textBaseline = 'top';
    ctx.fillText(slideTitle, SLIDE_PADDING, SLIDE_PADDING * 0.6, SLIDE_WIDTH - SLIDE_PADDING * 2);

    // Fit the chart into the space below the title, scaling up small charts
    // to fill the slide and down large ones to stay within bounds.
    const availW = SLIDE_WIDTH - SLIDE_PADDING * 2;
    const availH = SLIDE_HEIGHT - SLIDE_TITLE_HEIGHT - SLIDE_PADDING;
    const ratio = Math.min(availW / chartCanvas.width, availH / chartCanvas.height);
    const w = chartCanvas.width * ratio;
    const h = chartCanvas.height * ratio;
    const x = (SLIDE_WIDTH - w) / 2;
    const y = SLIDE_TITLE_HEIGHT + (availH - h) / 2;
    ctx.drawImage(chartCanvas, x, y, w, h);

    const filename = `${slugifyTitle(dashboardTitle, 'dashboard')}-${slugifyTitle(slideTitle, `chart-${i + 1}`)}.png`;
    downloadDataUrl(slide.toDataURL('image/png'), filename);
    exported++;

    // Stagger downloads — firing several synthetic <a download> clicks back
    // to back in one pass can trip the browser's "site is downloading
    // multiple files" prompt.
    if (i < cells.length - 1) await delay(250);
  }

  return exported;
}
